apiVersion: v1
kind: Service
metadata:
  namespace: anagram-ns
  labels:
    io.kompose.service: redis-service
  name: redis-service
spec:
  ports:
    - name: "http"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: redis-service
