management:
  endpoint:
    restart.enabled : true
    health.enabled : true
    info.enabled : true
spring:
  application:
    name: k8config
  cloud:
    kubernetes:
      reload:
        period: 1000
        enabled: true
      config:
        enabled: true
        name: k8config
        namespace: default
        sources:
          - name: myk8config
            namespace: default
