kind: ConfigMap
apiVersion: v1
metadata:
  name: anagram-configmap
  namespace: anagram-ns
data:
  spring.redis.host: redis-service
  spring.webflux.base-path: etechlog
  management.endpoints.web.base-path: /insights
